# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borsa', '0002_auto_20160916_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gearbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='borsa.Engine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='gearbox',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='borsa.Gearbox'),
            preserve_default=False,
        ),
    ]
