# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borsa', '0004_auto_20160916_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='gps',
            field=models.BooleanField(default=False, verbose_name='GPS'),
        ),
        migrations.AlterField(
            model_name='car',
            name='taxi',
            field=models.BooleanField(default=False, verbose_name='test'),
        ),
        migrations.AlterField(
            model_name='car',
            name='trc',
            field=models.BooleanField(default=False, verbose_name='Traction Control'),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='borsa.Color'),
            preserve_default=False,
        ),
    ]
