# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borsa', '0008_auto_20160920_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
