# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borsa', '0009_car_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='hp',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
