# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 08:21
from __future__ import unicode_literals

import borsa.models
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('borsa', '0011_auto_20161002_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to=borsa.models.photos_papka),
        ),
        migrations.AlterField(
            model_name='car',
            name='abs',
            field=models.BooleanField(default=False, verbose_name='Anti-lock braking system'),
        ),
        migrations.AlterField(
            model_name='car',
            name='acc',
            field=models.BooleanField(default=False, verbose_name='Air Conditioner'),
        ),
        migrations.AlterField(
            model_name='car',
            name='accjabka',
            field=models.BooleanField(default=False, verbose_name='Hladilna jabka'),
        ),
        migrations.AlterField(
            model_name='car',
            name='afl',
            field=models.BooleanField(default=False, verbose_name='Adaptive front lights'),
        ),
        migrations.AlterField(
            model_name='car',
            name='airbagf',
            field=models.BooleanField(default=False, verbose_name='Airbag front'),
        ),
        migrations.AlterField(
            model_name='car',
            name='airbagr',
            field=models.BooleanField(default=False, verbose_name='Airbag rear'),
        ),
        migrations.AlterField(
            model_name='car',
            name='airbags',
            field=models.BooleanField(default=False, verbose_name='Airbag side'),
        ),
        migrations.AlterField(
            model_name='car',
            name='airmatic',
            field=models.BooleanField(default=False, verbose_name='Adaptive Air Suspension'),
        ),
        migrations.AlterField(
            model_name='car',
            name='alarma',
            field=models.BooleanField(default=False, verbose_name='Alarm System'),
        ),
        migrations.AlterField(
            model_name='car',
            name='alkantara',
            field=models.BooleanField(default=False, verbose_name='Alkantara'),
        ),
        migrations.AlterField(
            model_name='car',
            name='aludjanti',
            field=models.BooleanField(default=False, verbose_name='Alloy Wheels'),
        ),
        migrations.AlterField(
            model_name='car',
            name='asr',
            field=models.BooleanField(default=False, verbose_name='Anti-Slip Regulation'),
        ),
        migrations.AlterField(
            model_name='car',
            name='ass',
            field=models.BooleanField(default=False, verbose_name='Auto Start Stop Function'),
        ),
        migrations.AlterField(
            model_name='car',
            name='audiosys',
            field=models.BooleanField(default=False, verbose_name='Audio System'),
        ),
        migrations.AlterField(
            model_name='car',
            name='barter',
            field=models.BooleanField(default=False, verbose_name='Barter'),
        ),
        migrations.AlterField(
            model_name='car',
            name='bas',
            field=models.BooleanField(default=False, verbose_name='Brake Assistant'),
        ),
        migrations.AlterField(
            model_name='car',
            name='boardpc',
            field=models.BooleanField(default=False, verbose_name='Board Computer'),
        ),
        migrations.AlterField(
            model_name='car',
            name='broniran',
            field=models.BooleanField(default=False, verbose_name='Bulletproof'),
        ),
        migrations.AlterField(
            model_name='car',
            name='bthf',
            field=models.BooleanField(default=False, verbose_name='Bluetooth Hands Free'),
        ),
        migrations.AlterField(
            model_name='car',
            name='ccontrol',
            field=models.BooleanField(default=False, verbose_name='Cruise Control'),
        ),
        migrations.AlterField(
            model_name='car',
            name='centralno',
            field=models.BooleanField(default=False, verbose_name='Central Locking System'),
        ),
        migrations.AlterField(
            model_name='car',
            name='chetirivrati',
            field=models.BooleanField(default=False, verbose_name='Four Door'),
        ),
        migrations.AlterField(
            model_name='car',
            name='crashed',
            field=models.BooleanField(default=False, verbose_name='Crashed'),
        ),
        migrations.AlterField(
            model_name='car',
            name='dbs',
            field=models.BooleanField(default=False, verbose_name='Dry Brake System'),
        ),
        migrations.AlterField(
            model_name='car',
            name='desenvolan',
            field=models.BooleanField(default=False, verbose_name='Right Hand Drive'),
        ),
        migrations.AlterField(
            model_name='car',
            name='diffblock',
            field=models.BooleanField(default=False, verbose_name='Differential Lock'),
        ),
        migrations.AlterField(
            model_name='car',
            name='distronic',
            field=models.BooleanField(default=False, verbose_name='Distronic'),
        ),
        migrations.AlterField(
            model_name='car',
            name='dpf',
            field=models.BooleanField(default=False, verbose_name='DPF'),
        ),
        migrations.AlterField(
            model_name='car',
            name='dsa',
            field=models.BooleanField(default=False, verbose_name='Dynamic Stability Assistance'),
        ),
        migrations.AlterField(
            model_name='car',
            name='dvdtv',
            field=models.BooleanField(default=False, verbose_name='DVD/TV'),
        ),
        migrations.AlterField(
            model_name='car',
            name='dvevrati',
            field=models.BooleanField(default=False, verbose_name='Two Door'),
        ),
        migrations.AlterField(
            model_name='car',
            name='ebd',
            field=models.BooleanField(default=False, verbose_name='Electronic Brakeforce Distribution'),
        ),
        migrations.AlterField(
            model_name='car',
            name='elmirrors',
            field=models.BooleanField(default=False, verbose_name='Electric Mirrors'),
        ),
        migrations.AlterField(
            model_name='car',
            name='elps',
            field=models.BooleanField(default=False, verbose_name='Electric Power Steering'),
        ),
        migrations.AlterField(
            model_name='car',
            name='elseats',
            field=models.BooleanField(default=False, verbose_name='Electric Seats'),
        ),
        migrations.AlterField(
            model_name='car',
            name='elsuspension',
            field=models.BooleanField(default=False, verbose_name='Electric Suspension'),
        ),
        migrations.AlterField(
            model_name='car',
            name='elwindows',
            field=models.BooleanField(default=False, verbose_name='Electric Windows'),
        ),
        migrations.AlterField(
            model_name='car',
            name='esp',
            field=models.BooleanField(default=False, verbose_name='Electronic Stability Program'),
        ),
        migrations.AlterField(
            model_name='car',
            name='forparts',
            field=models.BooleanField(default=False, verbose_name='For parts'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fwheating',
            field=models.BooleanField(default=False, verbose_name='Front Window Heating'),
        ),
        migrations.AlterField(
            model_name='car',
            name='grajdanska',
            field=models.BooleanField(default=False, verbose_name='Grajdanska'),
        ),
        migrations.AlterField(
            model_name='car',
            name='halogeni',
            field=models.BooleanField(default=False, verbose_name='Halogen Lights'),
        ),
        migrations.AlterField(
            model_name='car',
            name='hladilen',
            field=models.BooleanField(default=False, verbose_name='Hladilen'),
        ),
        migrations.AlterField(
            model_name='car',
            name='hlwash',
            field=models.BooleanField(default=False, verbose_name='Headlights Washing System'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imobilaizer',
            field=models.BooleanField(default=False, verbose_name='Immobilizer'),
        ),
        migrations.AlterField(
            model_name='car',
            name='integrale',
            field=models.BooleanField(default=False, verbose_name='4x4'),
        ),
        migrations.AlterField(
            model_name='car',
            name='kasko',
            field=models.BooleanField(default=False, verbose_name='Insurance'),
        ),
        migrations.AlterField(
            model_name='car',
            name='katafalka',
            field=models.BooleanField(default=False, verbose_name='Katafalka'),
        ),
        migrations.AlterField(
            model_name='car',
            name='keyless',
            field=models.BooleanField(default=False, verbose_name='Keyless Ignition'),
        ),
        migrations.AlterField(
            model_name='car',
            name='kojensalon',
            field=models.BooleanField(default=False, verbose_name='Leather Seats'),
        ),
        migrations.AlterField(
            model_name='car',
            name='ksenon',
            field=models.BooleanField(default=False, verbose_name='Xenon'),
        ),
        migrations.AlterField(
            model_name='car',
            name='ledfarove',
            field=models.BooleanField(default=False, verbose_name='Led headlights'),
        ),
        migrations.AlterField(
            model_name='car',
            name='lightsensor',
            field=models.BooleanField(default=False, verbose_name='Light Sensor'),
        ),
        migrations.AlterField(
            model_name='car',
            name='lineika',
            field=models.BooleanField(default=False, verbose_name='Ambulance'),
        ),
        migrations.AlterField(
            model_name='car',
            name='lizing',
            field=models.BooleanField(default=False, verbose_name='Leasing'),
        ),
        migrations.AlterField(
            model_name='car',
            name='lpg',
            field=models.BooleanField(default=False, verbose_name='LPG'),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borsa.Make', verbose_name='Make:'),
        ),
        migrations.AlterField(
            model_name='car',
            name='metalic',
            field=models.BooleanField(default=False, verbose_name='Metallic'),
        ),
        migrations.AlterField(
            model_name='car',
            name='metan',
            field=models.BooleanField(default=False, verbose_name='Metane'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mfv',
            field=models.BooleanField(default=False, verbose_name='Multifunctional Steering Wheel'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='make', chained_model_field='make', on_delete=django.db.models.deletion.CASCADE, to='borsa.Model', verbose_name='Model:'),
        ),
        migrations.AlterField(
            model_name='car',
            name='navi',
            field=models.BooleanField(default=False, verbose_name='Navigation'),
        ),
        migrations.AlterField(
            model_name='car',
            name='novvnos',
            field=models.BooleanField(default=False, verbose_name='Not registered'),
        ),
        migrations.AlterField(
            model_name='car',
            name='obslujen',
            field=models.BooleanField(default=False, verbose_name='Serviced'),
        ),
        migrations.AlterField(
            model_name='car',
            name='parkingsensor',
            field=models.BooleanField(default=False, verbose_name='Parking Sensor'),
        ),
        migrations.AlterField(
            model_name='car',
            name='pechka',
            field=models.BooleanField(default=False, verbose_name='Heating Unit'),
        ),
        migrations.AlterField(
            model_name='car',
            name='rainsensor',
            field=models.BooleanField(default=False, verbose_name='Rain Sensor'),
        ),
        migrations.AlterField(
            model_name='car',
            name='registriran',
            field=models.BooleanField(default=False, verbose_name='Registered'),
        ),
        migrations.AlterField(
            model_name='car',
            name='seatsheating',
            field=models.BooleanField(default=False, verbose_name='Seats Heating'),
        ),
        migrations.AlterField(
            model_name='car',
            name='sedemseats',
            field=models.BooleanField(default=False, verbose_name='7 seats'),
        ),
        migrations.AlterField(
            model_name='car',
            name='serviznaknijka',
            field=models.BooleanField(default=False, verbose_name='Service book'),
        ),
        migrations.AlterField(
            model_name='car',
            name='servo',
            field=models.BooleanField(default=False, verbose_name='Power Steering'),
        ),
        migrations.AlterField(
            model_name='car',
            name='shibidah',
            field=models.BooleanField(default=False, verbose_name='shibidah'),
        ),
        migrations.AlterField(
            model_name='car',
            name='spoileri',
            field=models.BooleanField(default=False, verbose_name='Spoilers'),
        ),
        migrations.AlterField(
            model_name='car',
            name='steptip',
            field=models.BooleanField(default=False, verbose_name='Steptronic/Tiptronic'),
        ),
        migrations.AlterField(
            model_name='car',
            name='swheat',
            field=models.BooleanField(default=False, verbose_name='Steering Wheel Heating'),
        ),
        migrations.AlterField(
            model_name='car',
            name='swreg',
            field=models.BooleanField(default=False, verbose_name='Steering Wheel Regulation'),
        ),
        migrations.AlterField(
            model_name='car',
            name='taxi',
            field=models.BooleanField(default=False, verbose_name='Taxi'),
        ),
        migrations.AlterField(
            model_name='car',
            name='teglich',
            field=models.BooleanField(default=False, verbose_name='Teglich'),
        ),
        migrations.AlterField(
            model_name='car',
            name='tpc',
            field=models.BooleanField(default=False, verbose_name='Tire Pressure Sensor'),
        ),
        migrations.AlterField(
            model_name='car',
            name='tuning',
            field=models.BooleanField(default=False, verbose_name='Tuning'),
        ),
        migrations.AlterField(
            model_name='car',
            name='ucheben',
            field=models.BooleanField(default=False, verbose_name='Ucheben'),
        ),
        migrations.AlterField(
            model_name='car',
            name='usbaux',
            field=models.BooleanField(default=False, verbose_name='USB/AUX'),
        ),
        migrations.AlterField(
            model_name='car',
            name='velurensalon',
            field=models.BooleanField(default=False, verbose_name='Veluren salon'),
        ),
        migrations.AlterField(
            model_name='car',
            name='wipersheating',
            field=models.BooleanField(default=False, verbose_name='Wipers Heating'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(choices=[(1920, 1920), (1921, 1921), (1922, 1922), (1923, 1923), (1924, 1924), (1925, 1925), (1926, 1926), (1927, 1927), (1928, 1928), (1929, 1929), (1930, 1930), (1931, 1931), (1932, 1932), (1933, 1933), (1934, 1934), (1935, 1935), (1936, 1936), (1937, 1937), (1938, 1938), (1939, 1939), (1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), ('', '---------')], default='', verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='car',
            name='zainvalid',
            field=models.BooleanField(default=False, verbose_name='Za invalid'),
        ),
    ]
