# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borsa', '0013_auto_20161014_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carphotos',
            name='carid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snimki', to='borsa.Car'),
        ),
    ]
