# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borsa', '0014_auto_20161014_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carphotos',
            old_name='carid',
            new_name='property',
        ),
    ]
