# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borsa', '0015_auto_20161014_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carphotos',
            old_name='photo',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='carphotos',
            name='property',
        ),
        migrations.AddField(
            model_name='carphotos',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='borsa.Car'),
            preserve_default=False,
        ),
    ]
