# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borsa', '0017_auto_20161014_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='images',
            new_name='image',
        ),
    ]
