# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borsa', '0018_auto_20161014_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.AddField(
            model_name='carphotos',
            name='car_image',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='borsa.Car'),
            preserve_default=False,
        ),
    ]
