# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borsa', '0019_auto_20161014_1823'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarPhotos',
            new_name='CarImage',
        ),
        migrations.RenameField(
            model_name='carimage',
            old_name='car_image',
            new_name='car',
        ),
    ]
